import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Layout from "@/components/layout";
import Card from "@/components/card";
import { getAllPosts } from "@/utils/funcs";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ postData }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Layout>
          <h1>Ciao sfoglia pure i nostri articoli!</h1>
          {postData.map((post, index) => (
            <Card key={index} post={post} />
          ))}
        </Layout>
      </main>
    </>
  );
}

export const getStaticProps = () => {
  const postData = getAllPosts();

  return {
    props: {
      postData,
    },
  };
};
